import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "../components/queryProvider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/redux.png" sizes="any" />
        <link rel="theme-color" content="fff" />
      </Head>
    
        <ReactQueryProvider>
          {children}
          <ReactQueryDevtools />
        </ReactQueryProvider>
        </body>
    </html>
  );
}
